### ISSUE TITLE
Trouble with ani.h file

### ISSUE THREAD

**Issue by Olive80** [VolosR/TTGOWeatherStation#6]
Hi VolosR, thanks to share your project
I have a trouble with animation but i don't know where it come from, can u help me please ?...
Oliver
![Capture](https://user-images.githubusercontent.com/58820544/118646347-62053d80-b7e0-11eb-8022-e913c7313252.PNG)

**Comment by echelon75** [comment]
Hi,
Same problem on my PC
Don't use ani.h in zip file and simply copy/paste any.h on github webpage:
[https://github.com/VolosR/TTGOWeatherStation/blob/main/ani.h](https://github.com/VolosR/TTGOWeatherStation/blob/main/ani.h)


See also this video : 
https://www.bing.com/videos/search?view=detail&mid=3EAD5B081E76A47527D63EAD5B081E76A47527D6&q=error%3A+stray+%27%5C357%27+in+program&shtp=GetUrl&shid=91861e74-b2ff-40ed-a50e-4fc089f1a042&shtk=SE9XIFRPIEZJWCBTVFJBWSBFUlJPUlMgMjczLDI3NywzMDIgJiAzNTcgSU4gQVJEVUlOTw%3D%3D&shdk=Ik5PIE1PUkUsIFN0cmF5IEVycm9ycyI%3D&shhk=e%2FkRRK061eRGtE9KihdDtxfL6uE3mgWrSqi0o%2FXWZ9I%3D&form=VDSHOT&shth=OSH.6UKA14KxeQBrobQ9I57Rng


Regards

Richard

**Comment by Olive80** [comment]
hi @echelon75 
thanks for the information...
I deleted the 1st row and it worked for me

**Comment by nikthefix** [comment]
Just delete the first 'int' and retype.. It seems that some non-ascii characters have crept in as is reflected by the arduino ide as it should highlight the 'int' in blue as a defined keyword.

**Comment by PGNetHun** [comment]
Hi! The problem is, that `ani.h` is an UTF-8 text file with BOM characters, Notepad++ tells it exactly. 
(first 3 bytes in file are the BOM bytes)
You can convert to simple UTF-8 text file withouth BOM with even with Notepad++
![image](https://user-images.githubusercontent.com/25751703/149033876-359a7b4f-9c44-49d1-94f9-835ce438e113.png)

**Comment by soharddbwarez** [comment]
My God am I happy that I look at the closed issues and read the answers, thanks to @PGNetHun I finally found what the issue was with the ani.h file and the Arduino IDE not wanting to compile because of an error that didn't seem to exist but after I opened the file with Notepad++ and converting it to a UTF-8 file without the BOM the issue went away.

Thank you so much for sharing this because without this piece of information I couldn't figure it out myself.
